config/routes.rb
Rails.application.routes.draw do
  get 'store/index'

  resources :users
  get 'manage/index'
  get 'manage/terms'
  root 'store#index'
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new 
	end
	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Friend As A Service',
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to :root
	end

end

app/controllers/manage_controller.rb
class ManageController < ApplicationController
  def index
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/manage_helper.rb
module ManageHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>! Now We Are Friends ..</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTaskRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
  	
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/terms.html.erb
After your lifelong experience with friends, you decided not to have "free" friends, they are the reason for your headache after all, so they need to pay for it. You came up with the idea of Friends as a Service (FaaS). You will charge every one of them $5/mo to stay friends with ME.

app/views/store/index.html.erb
<div class="container" style="text-align: center">
	<h1>Friend As A Service</h1>
	<p>Let's become friends for $5/month</p>
	<img src="https://i.imgur.com/o93GdGH.jpg" width="440" height="400">

	<%= form_tag charges_path do %>
	  <article>
	    <% if flash[:error].present? %>
	      <div id="error_explanation">
	        <p><%= flash[:error] %></p>
	      </div>
	    <% end %>
	    <label class="amount">
	      <span>Amount: $5.00</span>
	    </label>
	    <input id="terms" type="checkbox" name="terms"> i agree to the <a href="/manage/terms">terms of service</a><br><br>
	  </article>
	  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
	  		  Stripe.setPublishableKey('pk_test_2e2ZhYNuZFLu1ou1fxkUoEBl');
	          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
	          data-description="Friend As A Service"
	          data-amount="500"
	          data-billing-address="true"
	          data-shipping-address="true"
	          data-locale="auto"></script>
	<% end %>

</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :user_age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.age %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>